#!/bin/sh

uci -q batch << EOF
set system.@system[0].timezone='CST-8'
set system.@system[0].zonename='Asia/Shanghai'
set system.@system[0].cronloglevel='8'
set system.@system[0].conloglevel='7'

commit
EOF